#controller_manager_ns: controller_manager

controller_list:
 - name: abot_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints:
      - Joint0
      - Joint1
      - Joint2
      - Joint3
